# Generated by Django 6.0.7 on 2026-07-12 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('location', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('maintenance', 'En maintenance'), ('out_of_service', 'Hors service')], default='active', max_length=20)),
                ('criticality', models.CharField(choices=[('low', 'Basse'), ('medium', 'Moyenne'), ('high', 'Élevée')], default='medium', max_length=10)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
