# Generated by Django 6.0.7 on 2026-07-12 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('preventive', 'Maintenance préventive'), ('predictive', 'Risque de panne'), ('overdue', 'Intervention en retard')], max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Avertissement'), ('critical', 'Critique')], default='info', max_length=10)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='equipment.equipment')),
            ],
        ),
    ]
